# Constants for channels and ports
class Ids:
    LEFT_MOTOR = 0
    RIGHT_MOTOR = 1
    LEFT_ENCODER = (4, 5)
    RIGHT_ENCODER = (6, 7)
    SERVO = 4
    CONTROLLER = 0


class Robot:
    ENCODER_COUNTS_PER_MOTOR_SHAFT_REVOLUTION = 12.0
    GEAR_RATIO = (30.0 / 14.0) * (28.0 / 16.0) * (36.0 / 9.0) * (26.0 / 8.0)  # 48.75:1
    ENCODER_COUNTS_PER_REVOLUTION = (
        ENCODER_COUNTS_PER_MOTOR_SHAFT_REVOLUTION * GEAR_RATIO
    )  # 585.0
    WHEEL_DIAMETER_MM = 60.0
    TRACK_WIDTH_INCHES = 6.0
    GYRO_NOISE_THRESHOLD = 0.025


LED_BLINK_TIME = 0.25
